"""Temporal card state: tracking, acceptance, table assembly, audit metrics."""

from .accept import accept_table
from .table import TableState, build_table_state
from .tracker import CardTracker
from .types import (
    BOARD_MIN_MARGIN,
    BOARD_MIN_STABLE_FRAMES,
    BOARD_MIN_TEMPORAL,
    BOARD_MIN_TOP,
    BOX_STABLE_IOU,
    CardObservation,
    EMA_ALPHA,
    HOLE_MIN_MARGIN,
    HOLE_MIN_STABLE_FRAMES,
    HOLE_MIN_TEMPORAL,
    HOLE_MIN_TOP,
    HOLE_STRONG_MARGIN,
    HOLE_STRONG_STABLE_FRAMES,
    HOLE_STRONG_TOP,
    IOU_MATCH,
    LOW_MARGIN_WEIGHT,
    MARGIN_WEAK,
    MAX_MISSED_FRAMES,
    RawDet,
    SLOT_BOARD,
    SLOT_HERO,
    TRANSITIONING,
    UNKNOWN,
    UNKNOWN_LABEL,
    VISIBLE,
    normalize_probs,
    rank_margin,
    suit_margin,
    top_from_probs,
)

__all__ = [
    "BOARD_MIN_MARGIN",
    "BOARD_MIN_STABLE_FRAMES",
    "BOARD_MIN_TEMPORAL",
    "BOARD_MIN_TOP",
    "BOX_STABLE_IOU",
    "CardObservation",
    "CardTracker",
    "EMA_ALPHA",
    "HOLE_MIN_MARGIN",
    "HOLE_MIN_STABLE_FRAMES",
    "HOLE_MIN_TEMPORAL",
    "HOLE_MIN_TOP",
    "HOLE_STRONG_MARGIN",
    "HOLE_STRONG_STABLE_FRAMES",
    "HOLE_STRONG_TOP",
    "IOU_MATCH",
    "LOW_MARGIN_WEIGHT",
    "MARGIN_WEAK",
    "MAX_MISSED_FRAMES",
    "RawDet",
    "SLOT_BOARD",
    "SLOT_HERO",
    "TRANSITIONING",
    "TableState",
    "UNKNOWN",
    "UNKNOWN_LABEL",
    "VISIBLE",
    "accept_table",
    "build_table_state",
    "normalize_probs",
    "rank_margin",
    "suit_margin",
    "top_from_probs",
]
